version: "3"
services:
  influxdb:
    image: influxdb:latest
    restart: always
    environment:
      - INFLUXDB_ADMIN_ENABLED=true 
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=francescogaggini
      - INFLUXDB_ADMIN_PASSWORD=dxzr5962
    ports:
      - 8086:8086
    volumes:
      - ./myInfluxVolume:/var/lib/influxdb2
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 3050:80

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app